#!/usr/bin/env bash

set -euo pipefail

hidraw_args=$(for i in /dev/hidraw*; do echo -n "--device=${i} "; done;)

exec docker run --init ${hidraw_args} --rm -i docker.io/hugojosefson/g513-led -k "$@"
