#!/usr/bin/env bash

set -euo pipefail

color=${1:-66aa44}
hidraw_args=$(for i in /dev/hidraw*; do echo -n "--device=${i} "; done;)

exec docker run --init ${hidraw_args} --rm -i docker.io/hugojosefson/g513-led -fx color all ${color}
